<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>WORLD HAPPINESS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Regression_lineaire_files/libs/clipboard/clipboard.min.js"></script>
<script src="Regression_lineaire_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Regression_lineaire_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Regression_lineaire_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Regression_lineaire_files/libs/quarto-html/popper.min.js"></script>
<script src="Regression_lineaire_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Regression_lineaire_files/libs/quarto-html/anchor.min.js"></script>
<link href="Regression_lineaire_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Regression_lineaire_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Regression_lineaire_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Regression_lineaire_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Regression_lineaire_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><strong>WORLD HAPPINESS</strong></h1>
<p class="subtitle lead"><strong>Régression linéaire et choix de modèle</strong></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<ol type="1">
<li><h5 id="chargement-des-données-et-sélection-des-variables" class="anchored">Chargement des données et sélection des variables</h5></li>
</ol>
<p>Le fichier nettoyé dans le notebook <code>nettoyage_des_données.ipynb</code>, <code>world_happiness_2015_clean.csv</code>, est utilisé dans le cadre de cette première régression linéaire.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data15 <span class="ot">&lt;-</span> <span class="fu">file.path</span>(<span class="st">".."</span>, <span class="st">"data"</span>, <span class="st">"clean"</span>, <span class="st">"world_happiness_2015_clean.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df15 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(data15, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable réponse : happiness_score</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables explicatives : les mêmes que pour l’ACP</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>vars_x <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"gdp_log"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"life_expectancy"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"freedom_to_choose"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"generosity"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cpi"</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"unemployment_rate"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"active_population_rate"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"urban_population_rate"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"voice_accountability"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"government_effectiveness"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"co2_emissions_per_capita"</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"temperature_change_from_ghg"</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>form <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"happiness_score ~"</span>, <span class="fu">paste</span>(vars_x, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>mod_2015 <span class="ot">&lt;-</span> <span class="fu">lm</span>(form, <span class="at">data =</span> df15)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2015)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form, data = df15)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.46003 -0.28442 -0.01139  0.40316  1.36681 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)                 -3.740265   1.483563  -2.521  0.01310 * 
gdp_log                      0.519072   0.160979   3.224  0.00165 **
life_expectancy              0.050414   0.016575   3.042  0.00293 **
freedom_to_choose            1.119933   0.348662   3.212  0.00172 **
generosity                   0.293216   0.380823   0.770  0.44295   
cpi                          0.006395   0.009059   0.706  0.48165   
unemployment_rate           -0.030998   0.012311  -2.518  0.01322 * 
active_population_rate      -0.011530   0.015207  -0.758  0.44992   
urban_population_rate        0.006214   0.004451   1.396  0.16552   
voice_accountability         0.157334   0.109011   1.443  0.15173   
government_effectiveness    -0.360131   0.219002  -1.644  0.10289   
co2_emissions_per_capita    -0.001167   0.018208  -0.064  0.94899   
temperature_change_from_ghg  2.082852   1.772169   1.175  0.24236   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5795 on 112 degrees of freedom
Multiple R-squared:  0.7713,    Adjusted R-squared:  0.7468 
F-statistic: 31.48 on 12 and 112 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>En 2015, le modèle a un R² de 0,7713 et un R² ajusté de 0,7468. Le test global est très significatif (p-value &lt; 2.2e-16), ce qui indique que l’ensemble des variables explicatives contribue à expliquer <code>happiness_score</code>.</p>
<p>Au seuil de 5%, les variables significatives sont <code>gdp_log</code> (effet positif), <code>life_expectancy</code> (effet positif), <code>freedom_to_choose</code> (effet positif) et <code>unemployment_rate</code> (effet négatif). Dans cette régression 2015, <code>generosity</code> et <code>cpi</code> ne sont pas significatives, et plusieurs variables institutionnelles et environnementales ne sont pas significatives non plus selon les p-values affichées.</p>
<table class="caption-top table">
<caption>Modèle 2015. Coefficients triés par p-value.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gdp_log</td>
<td style="text-align: right;">0.5191</td>
<td style="text-align: right;">0.1610</td>
<td style="text-align: right;">3.2245</td>
<td style="text-align: right;">0.0017</td>
</tr>
<tr class="even">
<td style="text-align: left;">freedom_to_choose</td>
<td style="text-align: right;">1.1199</td>
<td style="text-align: right;">0.3487</td>
<td style="text-align: right;">3.2121</td>
<td style="text-align: right;">0.0017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">life_expectancy</td>
<td style="text-align: right;">0.0504</td>
<td style="text-align: right;">0.0166</td>
<td style="text-align: right;">3.0415</td>
<td style="text-align: right;">0.0029</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-3.7403</td>
<td style="text-align: right;">1.4836</td>
<td style="text-align: right;">-2.5211</td>
<td style="text-align: right;">0.0131</td>
</tr>
<tr class="odd">
<td style="text-align: left;">unemployment_rate</td>
<td style="text-align: right;">-0.0310</td>
<td style="text-align: right;">0.0123</td>
<td style="text-align: right;">-2.5178</td>
<td style="text-align: right;">0.0132</td>
</tr>
<tr class="even">
<td style="text-align: left;">government_effectiveness</td>
<td style="text-align: right;">-0.3601</td>
<td style="text-align: right;">0.2190</td>
<td style="text-align: right;">-1.6444</td>
<td style="text-align: right;">0.1029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">voice_accountability</td>
<td style="text-align: right;">0.1573</td>
<td style="text-align: right;">0.1090</td>
<td style="text-align: right;">1.4433</td>
<td style="text-align: right;">0.1517</td>
</tr>
<tr class="even">
<td style="text-align: left;">urban_population_rate</td>
<td style="text-align: right;">0.0062</td>
<td style="text-align: right;">0.0045</td>
<td style="text-align: right;">1.3958</td>
<td style="text-align: right;">0.1655</td>
</tr>
<tr class="odd">
<td style="text-align: left;">temperature_change_from_ghg</td>
<td style="text-align: right;">2.0829</td>
<td style="text-align: right;">1.7722</td>
<td style="text-align: right;">1.1753</td>
<td style="text-align: right;">0.2424</td>
</tr>
<tr class="even">
<td style="text-align: left;">generosity</td>
<td style="text-align: right;">0.2932</td>
<td style="text-align: right;">0.3808</td>
<td style="text-align: right;">0.7700</td>
<td style="text-align: right;">0.4429</td>
</tr>
<tr class="odd">
<td style="text-align: left;">active_population_rate</td>
<td style="text-align: right;">-0.0115</td>
<td style="text-align: right;">0.0152</td>
<td style="text-align: right;">-0.7582</td>
<td style="text-align: right;">0.4499</td>
</tr>
<tr class="even">
<td style="text-align: left;">cpi</td>
<td style="text-align: right;">0.0064</td>
<td style="text-align: right;">0.0091</td>
<td style="text-align: right;">0.7060</td>
<td style="text-align: right;">0.4816</td>
</tr>
<tr class="odd">
<td style="text-align: left;">co2_emissions_per_capita</td>
<td style="text-align: right;">-0.0012</td>
<td style="text-align: right;">0.0182</td>
<td style="text-align: right;">-0.0641</td>
<td style="text-align: right;">0.9490</td>
</tr>
</tbody>
</table>
<p>Le tableau montre l’ordre de significativité en 2015. Les plus petites p-values concernent <code>gdp_log</code>, <code>freedom_to_choose</code>, <code>life_expectancy</code>, puis <code>unemployment_rate</code>. Les variables comme <code>co2_emissions_per_capita</code> et <code>cpi</code> ont des p-values élevées dans ce modèle.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/obs_vs_pred_2015.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>Pour comparer, on répète ce modèle pour le fichier <code>world_happiness_2023_clean.csv</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data23 <span class="ot">&lt;-</span> <span class="fu">file.path</span>(<span class="st">".."</span>, <span class="st">"data"</span>, <span class="st">"clean"</span>, <span class="st">"world_happiness_2023_clean.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df23 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(data23, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>form <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"happiness_score ~"</span>, <span class="fu">paste</span>(vars_x, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>mod_2023 <span class="ot">&lt;-</span> <span class="fu">lm</span>(form, <span class="at">data =</span> df23)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2023)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form, data = df23)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.83986 -0.20558  0.02126  0.28336  1.06485 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -0.989568   1.179896  -0.839   0.4034    
gdp_log                      0.630622   0.127589   4.943 2.72e-06 ***
life_expectancy              0.005997   0.014934   0.402   0.6888    
freedom_to_choose            2.193645   0.350640   6.256 7.42e-09 ***
generosity                   0.348890   0.305302   1.143   0.2556    
cpi                         -0.002129   0.008694  -0.245   0.8070    
unemployment_rate           -0.022679   0.012062  -1.880   0.0627 .  
active_population_rate      -0.029662   0.014745  -2.012   0.0467 *  
urban_population_rate        0.005644   0.003660   1.542   0.1259    
voice_accountability         0.245835   0.094116   2.612   0.0102 *  
government_effectiveness    -0.174545   0.180766  -0.966   0.3363    
co2_emissions_per_capita     0.014214   0.017362   0.819   0.4147    
temperature_change_from_ghg -0.164481   1.415092  -0.116   0.9077    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5232 on 112 degrees of freedom
Multiple R-squared:  0.8101,    Adjusted R-squared:  0.7898 
F-statistic: 39.82 on 12 and 112 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<table class="caption-top table">
<caption>Modèle 2023. Coefficients triés par p-value.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">freedom_to_choose</td>
<td style="text-align: right;">2.1936</td>
<td style="text-align: right;">0.3506</td>
<td style="text-align: right;">6.2561</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">gdp_log</td>
<td style="text-align: right;">0.6306</td>
<td style="text-align: right;">0.1276</td>
<td style="text-align: right;">4.9426</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">voice_accountability</td>
<td style="text-align: right;">0.2458</td>
<td style="text-align: right;">0.0941</td>
<td style="text-align: right;">2.6120</td>
<td style="text-align: right;">0.0102</td>
</tr>
<tr class="even">
<td style="text-align: left;">active_population_rate</td>
<td style="text-align: right;">-0.0297</td>
<td style="text-align: right;">0.0147</td>
<td style="text-align: right;">-2.0116</td>
<td style="text-align: right;">0.0467</td>
</tr>
<tr class="odd">
<td style="text-align: left;">unemployment_rate</td>
<td style="text-align: right;">-0.0227</td>
<td style="text-align: right;">0.0121</td>
<td style="text-align: right;">-1.8803</td>
<td style="text-align: right;">0.0627</td>
</tr>
<tr class="even">
<td style="text-align: left;">urban_population_rate</td>
<td style="text-align: right;">0.0056</td>
<td style="text-align: right;">0.0037</td>
<td style="text-align: right;">1.5421</td>
<td style="text-align: right;">0.1259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">generosity</td>
<td style="text-align: right;">0.3489</td>
<td style="text-align: right;">0.3053</td>
<td style="text-align: right;">1.1428</td>
<td style="text-align: right;">0.2556</td>
</tr>
<tr class="even">
<td style="text-align: left;">government_effectiveness</td>
<td style="text-align: right;">-0.1745</td>
<td style="text-align: right;">0.1808</td>
<td style="text-align: right;">-0.9656</td>
<td style="text-align: right;">0.3363</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.9896</td>
<td style="text-align: right;">1.1799</td>
<td style="text-align: right;">-0.8387</td>
<td style="text-align: right;">0.4034</td>
</tr>
<tr class="even">
<td style="text-align: left;">co2_emissions_per_capita</td>
<td style="text-align: right;">0.0142</td>
<td style="text-align: right;">0.0174</td>
<td style="text-align: right;">0.8187</td>
<td style="text-align: right;">0.4147</td>
</tr>
<tr class="odd">
<td style="text-align: left;">life_expectancy</td>
<td style="text-align: right;">0.0060</td>
<td style="text-align: right;">0.0149</td>
<td style="text-align: right;">0.4016</td>
<td style="text-align: right;">0.6888</td>
</tr>
<tr class="even">
<td style="text-align: left;">cpi</td>
<td style="text-align: right;">-0.0021</td>
<td style="text-align: right;">0.0087</td>
<td style="text-align: right;">-0.2449</td>
<td style="text-align: right;">0.8070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">temperature_change_from_ghg</td>
<td style="text-align: right;">-0.1645</td>
<td style="text-align: right;">1.4151</td>
<td style="text-align: right;">-0.1162</td>
<td style="text-align: right;">0.9077</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/obs_vs_pred_2023.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>En 2023, le modèle explique environ 81 % de la variabilité du score de bonheur (R² = 0,8101, R² ajusté = 0,7898), soit légèrement plus qu’en 2015. Le test global de Fisher reste très significatif (p-value &lt; 2.2e-16), ce qui confirme que l’ensemble des variables apporte une information utile pour expliquer <code>happiness_score</code>.</p>
<p>Au seuil de 5 %, les variables significatives en 2023 sont :</p>
<ul>
<li><p><code>freedom_to_choose</code> : effet positif et très marqué, c’est la variable la plus significative du modèle (p-value ≈ 7.42e-09),</p></li>
<li><p><code>gdp_log</code> : effet positif et significatif (p-value ≈ 2.72e-06),</p></li>
<li><p><code>voice_accountability</code> : effet positif et significatif (p-value ≈ 0.0102),</p></li>
<li><p><code>active_population_rate</code> : effet négatif et significatif (p-value ≈ 0.0467).</p></li>
</ul>
<p><code>unemployment_rate</code> est faiblement significative au seuil de 10 % (p-value ≈ 0.0627) et garde un effet négatif, mais elle n’est pas significative au seuil de 5 %.</p>
<p>À l’inverse, <code>life_expectancy</code>, <code>generosity</code>, <code>cpi</code>, <code>government_effectiveness</code> et les variables environnementales (<code>co2_emissions_per_capita</code>, <code>temperature_change_from_ghg</code>) ne sont pas significatives dans ce modèle 2023 selon les p-values affichées.</p>
<p>En résumé, entre 2015 et 2023, le pouvoir explicatif du modèle augmente légèrement (R² passe d’environ 0,77 à 0,81). Les effets robustes et stables concernent surtout <code>gdp_log</code> et <code>freedom_to_choose</code> (positifs). En 2023, des variables institutionnelles et démographiques comme <code>voice_accountability</code> (positif) et <code>active_population_rate</code> (négatif) ressortent, tandis que <code>cpi</code> change de signe par rapport à 2015 mais reste non significative, donc ce point ne doit pas être interprété comme un résultat solide à ce stade.</p>
<ol start="2" type="1">
<li><h5 id="validation-des-modèles-linéaires-graphes-de-résidus" class="anchored">Validation des modèles linéaires (graphes de résidus)</h5></li>
</ol>
<p>À cette étape, on vérifie visuellement les hypothèses du modèle linéaire (linéarité, normalité des résidus, variance constante, et présence éventuelle de points influents)</p>
<ul>
<li>Pour le modèle 2015 :</li>
</ul>
<p><strong><em>Résidus / valeurs ajustées</em></strong></p>
<p>Le nuage est globalement centré autour de 0. La courbe rouge montre une légère forme en U très faible, ce qui suggère une non-linéarité légère mais limitée. On observe quelques résidus atypiques, étiquetés comme 14, 109 et 60, sans structure dominante.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_residus_vs_ajustes_2015.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>QQ-plot</em></strong></p>
<p>Les points suivent bien la droite au centre, mais on voit des écarts dans les extrémités, surtout dans la queue gauche (ex. 60, 109) et dans la queue droite (ex. 140). La normalité est donc globalement raisonnable, avec des queues un peu plus “lourdes” que la normale.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_qqplot_2015.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Scale-Location</em></strong></p>
<p>La dispersion des résidus standardisés est assez stable sur l’ensemble des valeurs ajustées. La courbe rouge est légèrement bombée au milieu, mais l’hétéroscédasticité semble faible à modérée, et ne remet pas en cause l’usage du modèle.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_scale_location_2015.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Résidus standardisés / leverage</em></strong></p>
<p>La majorité des points ont un leverage faible. Un point à leverage très élevé est visible (à droite), ce qui peut indiquer un pays particulièrement atypique sur les variables explicatives. Les distances de Cook ne semblent pas franchir de seuil critique, mais ces observations méritent d’être surveillées car elles peuvent influencer certains coefficients.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_residus_vs_leverage_2015.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Pour le modèle 2023 :</li>
</ul>
<p><strong><em>Résidus / valeurs ajustées</em></strong></p>
<p>Le nuage reste globalement centré autour de 0, mais la courbe rouge montre une tendance légèrement décroissante quand les valeurs ajustées augmentent. Cela indique un biais léger selon le niveau de bonheur, donc une non-linéarité plus marquée qu’en 2015.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_residus_vs_ajustes_2023.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>QQ-plot</em></strong></p>
<p>L’écart à la droite est plus visible qu’en 2015, surtout dans la queue gauche avec quelques points très extrêmes (ex. 124, 121, 116). La normalité des résidus est donc moins bien respectée en 2023, principalement à cause de ces observations atypiques.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_qqplot_2023.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Scale-Location</em></strong></p>
<p>La courbe rouge décroît globalement, ce qui suggère une variance des résidus un peu plus forte pour les valeurs ajustées faibles, puis plus faible pour les valeurs ajustées élevées. On est sur une hétéroscédasticité modérée.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_scale_location_2023.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Résidus standardisés / leverage</em></strong></p>
<p>Quelques points combinent résidus importants et leverage non négligeable (ex. 124, 121), ce qui les rend potentiellement influents. Là encore, rien n’indique une invalidité totale du modèle, mais ces pays peuvent peser sur l’estimation de certains paramètres.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/diag_residus_vs_leverage_2023.png" class="img-fluid figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p>En résumé, le modèle linéaire est globalement satisfaisant en 2015. En 2023, les diagnostics suggèrent davantage de non-linéarité, une normalité des résidus moins bonne à cause de quelques pays extrêmes, et une hétéroscédasticité modérée. Le modèle est exploitable, mais l’interprétation des coefficients doit être faite avec plus de prudence, en particulier à cause des observations potentiellement influentes.</p>
<ol start="3" type="1">
<li><h5 id="choix-de-modèle-linéaire-pour-2015-et-2023" class="anchored">Choix de modèle linéaire pour 2015 et 2023</h5></li>
</ol>
<p>On réduit d’abord le modèle en retirant la variable <code>generosity</code>, qui n’était pas significative dans le modèle complet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># - generosity</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>vars_x_red <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(vars_x, <span class="st">"generosity"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>form_red <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"happiness_score ~"</span>, <span class="fu">paste</span>(vars_x_red, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>mod_2015_red <span class="ot">&lt;-</span> <span class="fu">lm</span>(form_red, <span class="at">data =</span> df15)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2015_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form_red, data = df15)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.41874 -0.28059  0.02539  0.41702  1.34394 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -3.845049   1.474643  -2.607 0.010353 *  
gdp_log                      0.522435   0.160629   3.252 0.001509 ** 
life_expectancy              0.051751   0.016454   3.145 0.002122 ** 
freedom_to_choose            1.176074   0.340338   3.456 0.000774 ***
cpi                          0.007576   0.008912   0.850 0.397050    
unemployment_rate           -0.033276   0.011929  -2.790 0.006197 ** 
active_population_rate      -0.010912   0.015158  -0.720 0.473109    
urban_population_rate        0.005492   0.004344   1.264 0.208708    
voice_accountability         0.158645   0.108801   1.458 0.147581    
government_effectiveness    -0.381649   0.216820  -1.760 0.081078 .  
co2_emissions_per_capita    -0.002050   0.018140  -0.113 0.910205    
temperature_change_from_ghg  2.113724   1.768521   1.195 0.234514    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5784 on 113 degrees of freedom
Multiple R-squared:  0.7701,    Adjusted R-squared:  0.7477 
F-statistic: 34.41 on 11 and 113 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaison AIC / BIC entre modèle complet et réduit</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_2015, mod_2015_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             df      AIC
mod_2015     14 232.6054
mod_2015_red 13 231.2652</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_2015, mod_2015_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             df      BIC
mod_2015     14 272.2017
mod_2015_red 13 268.0333</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélection automatique par AIC (stepwise, départ du modèle complet)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mod_2015_step <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(mod_2015, <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2015_step)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_score ~ gdp_log + life_expectancy + freedom_to_choose + 
    unemployment_rate + urban_population_rate + voice_accountability + 
    government_effectiveness, data = df15)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.51288 -0.27048  0.04875  0.40831  1.24732 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              -3.161703   1.175568  -2.690 0.008202 ** 
gdp_log                   0.480229   0.140073   3.428 0.000839 ***
life_expectancy           0.042080   0.014285   2.946 0.003888 ** 
freedom_to_choose         1.176151   0.329757   3.567 0.000525 ***
unemployment_rate        -0.034748   0.011535  -3.012 0.003178 ** 
urban_population_rate     0.006819   0.004152   1.642 0.103222    
voice_accountability      0.209666   0.086499   2.424 0.016886 *  
government_effectiveness -0.223188   0.144637  -1.543 0.125509    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5752 on 117 degrees of freedom
Multiple R-squared:  0.7646,    Adjusted R-squared:  0.7505 
F-statistic: 54.28 on 7 and 117 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Le modèle réduit conserve un pouvoir explicatif pratiquement identique (R² = 0,7701 et R² ajusté = 0,7477, contre 0,7713 et 0,7468 pour le modèle complet). Le test global reste très significatif (p-value &lt; 2.2e-16).</p>
<p>Au seuil de 5 %, les variables significatives dans le modèle réduit 2015 sont :</p>
<ul>
<li><code>gdp_log</code> (effet positif, p = 0,0015),</li>
<li><code>life_expectancy</code> (effet positif, p = 0,0021),</li>
<li><code>freedom_to_choose</code> (effet positif, p = 0,0008),</li>
<li><code>unemployment_rate</code> (effet négatif, p = 0,0062)</li>
</ul>
<p>Les critères d’information confirment l’intérêt de supprimer generosity, l’AIC passe de 232,61 (modèle complet) à 231,27 (modèle réduit) et le BIC passe de 272,20 à 268,03. Le modèle réduit est donc légèrement meilleur, tout en restant plus parcimonieux.</p>
<p>La sélection automatique par AIC (stepAIC) retient un modèle encore plus parcimonieux à 7 variables : <code>gdp_log</code>, <code>life_expectancy</code>, <code>freedom_to_choose</code>, <code>unemployment_rate</code>, <code>urban_population_rate</code>, <code>voice_accountability</code> et <code>government_effectiveness</code>.</p>
<p>Dans ce modèle, les effets les plus robustes restent <code>gdp_log</code>, <code>life_expectancy</code>, <code>freedom_to_choose</code> et <code>unemployment_rate</code>, qui sont toutes significatives au seuil de 1 % et <code>voice_accountability</code> qui devient significative au seuil de 5 %. Le R² ajusté reste du même ordre (0,7505).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mod_2023_red <span class="ot">&lt;-</span> <span class="fu">lm</span>(form_red, <span class="at">data =</span> df23)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2023_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form_red, data = df23)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.85214 -0.23279  0.05078  0.26420  1.06617 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -0.7942229  1.1690268  -0.679  0.49828    
gdp_log                      0.6145872  0.1269864   4.840 4.15e-06 ***
life_expectancy              0.0044581  0.0148935   0.299  0.76523    
freedom_to_choose            2.2620652  0.3459577   6.539 1.87e-09 ***
cpi                         -0.0003963  0.0085725  -0.046  0.96321    
unemployment_rate           -0.0265506  0.0115919  -2.290  0.02385 *  
active_population_rate      -0.0280657  0.0146989  -1.909  0.05875 .  
urban_population_rate        0.0053056  0.0036529   1.452  0.14915    
voice_accountability         0.2525579  0.0940595   2.685  0.00834 ** 
government_effectiveness    -0.2076210  0.1786755  -1.162  0.24768    
co2_emissions_per_capita     0.0180486  0.0170576   1.058  0.29227    
temperature_change_from_ghg -0.0641539  1.4142769  -0.045  0.96390    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5239 on 113 degrees of freedom
Multiple R-squared:  0.8079,    Adjusted R-squared:  0.7892 
F-statistic:  43.2 on 11 and 113 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaison AIC / BIC entre modèle complet et réduit</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_2023, mod_2023_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             df      AIC
mod_2023     14 207.0448
mod_2023_red 13 206.4939</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_2023, mod_2023_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             df      BIC
mod_2023     14 246.6412
mod_2023_red 13 243.2619</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélection automatique par AIC (stepwise, départ du modèle complet)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mod_2023_step <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(mod_2023, <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2023_step)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_score ~ gdp_log + freedom_to_choose + 
    unemployment_rate + active_population_rate + urban_population_rate + 
    voice_accountability + government_effectiveness, data = df23)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.84216 -0.22855  0.06355  0.28111  1.04128 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              -1.163995   0.860692  -1.352  0.17886    
gdp_log                   0.673531   0.102924   6.544 1.66e-09 ***
freedom_to_choose         2.229990   0.335836   6.640 1.03e-09 ***
unemployment_rate        -0.027973   0.011279  -2.480  0.01456 *  
active_population_rate   -0.025172   0.013067  -1.926  0.05648 .  
urban_population_rate     0.005775   0.003563   1.621  0.10777    
voice_accountability      0.216720   0.078065   2.776  0.00641 ** 
government_effectiveness -0.187071   0.108624  -1.722  0.08768 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5175 on 117 degrees of freedom
Multiple R-squared:  0.8059,    Adjusted R-squared:  0.7943 
F-statistic: 69.39 on 7 and 117 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>En 2023, le modèle réduit conserve un excellent pouvoir explicatif (R² = 0,8079, R² ajusté = 0,7892), très proche du modèle complet (R² = 0,8101, R² ajusté = 0,7898). Le test global reste très significatif (p-value &lt; 2.2e-16).</p>
<p>Au seuil de 5 %, les variables significatives dans le modèle réduit 2023 sont :</p>
<ul>
<li><code>gdp_log</code> (effet positif, p = 4,15e-06)</li>
<li><code>freedom_to_choose</code> (effet positif, p = 1,87e-09)</li>
<li><code>unemployment_rate</code> (effet négatif, p = 0,0239)</li>
<li><code>voice_accountability</code> (effet positif, p = 0,0083)</li>
<li><code>active_population_rate</code> est proche du seuil de 5 % (p = 0,0588), donc significative au seuil de 10 %.</li>
</ul>
<p>Les critères AIC/BIC confirment que retirer <code>generosity</code> améliore légèrement le modèle : AIC passe de 207,04 (complet) à 206,49 (réduit) et BIC passe de 246,64 à 243,26. Le modèle réduit est donc préférable au modèle complet du point de vue parcimonie vs ajustement.</p>
<p>La sélection automatique par AIC (stepAIC) retient un modèle à les mêmes 7 variables : <code>gdp_log</code>, <code>freedom_to_choose</code>, <code>unemployment_rate</code>, <code>active_population_rate</code>, <code>urban_population_rate</code>, <code>voice_accountability</code>, <code>government_effectiveness</code>. Le pouvoir explicatif reste très proche (R² ajusté = 0,7943).</p>
<p>Dans ce modèle, les variables significatives au seuil de 5 % sont <code>gdp_log</code>, <code>freedom_to_choose</code>, <code>unemployment_rate</code> et <code>voice_accountability</code>. <code>active_population_rate</code> et <code>government_effectiveness</code> deviennent discutables au seuil de 10 %.</p>
<p>Au final, pour 2015 comme pour 2023, la suppression de <code>generosity</code> est justifiée car elle ne dégrade pas la qualité d’ajustement et améliore légèrement AIC/BIC. Les modèles stepAIC proposent ensuite des versions plus parcimonieuses, avec des R² ajustés très proches. Dans les deux années, les déterminants les plus robustes sont <code>gdp_log</code> et <code>freedom_to_choose</code> (effets positifs) et <code>unemployment_rate</code> (effet négatif), avec en plus un rôle institutionnel <code>voice_accountability</code> (effet positif), surtout visible en 2023.</p>
<ol start="4" type="1">
<li><h5 id="vérification-de-la-colinéarité-vif" class="anchored">Vérification de la colinéarité, VIF</h5></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod_2015_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    gdp_log             life_expectancy 
                  11.608275                    6.323862 
          freedom_to_choose                         cpi 
                   2.069180                   11.867505 
          unemployment_rate      active_population_rate 
                   1.672046                    3.521501 
      urban_population_rate        voice_accountability 
                   3.236580                    3.663989 
   government_effectiveness    co2_emissions_per_capita 
                  16.637089                    3.027073 
temperature_change_from_ghg 
                   1.107005 </code></pre>
</div>
</div>
<p>En 2015, plusieurs VIF dépassent nettement 10 : - <code>government_effectiveness</code> : 16,64 - <code>cpi</code> : 11,87 - <code>gdp_log</code> : 11,61</p>
<p>De plus, <code>life_expectancy</code> est également élevé (VIF = 6,32), ce qui indique une colinéarité non négligeable.</p>
<p>Cela suggère une forte redondance entre les variables de niveau de développement et de qualité institutionnelle (richesse, santé, efficacité gouvernementale, perception de la corruption). Dans ce contexte, il est normal que certaines variables deviennent non significatives individuellement malgré un modèle global très bon, car elles partagent une partie de la même information.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/corr_heatmap_2015.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod_2023_red)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    gdp_log             life_expectancy 
                   8.948924                    5.108596 
          freedom_to_choose                         cpi 
                   1.933336                   11.712507 
          unemployment_rate      active_population_rate 
                   1.324041                    2.717249 
      urban_population_rate        voice_accountability 
                   2.641216                    3.660104 
   government_effectiveness    co2_emissions_per_capita 
                  13.057440                    2.495336 
temperature_change_from_ghg 
                   1.109757 </code></pre>
</div>
</div>
<p>En 2023, la colinéarité reste présente mais est légèrement plus faible sur certaines variables : - <code>government_effectiveness</code> : 13,06 (reste &gt; 10) - <code>cpi</code> : 11,71 (reste &gt; 10) - <code>gdp_log</code> : 8,95 (passe sous 10) - <code>life_expectancy</code> : 5,11 (juste au-dessus de 5)</p>
<p>On observe donc une colinéarité toujours importante autour du bloc institutionnel (<code>government_effectiveness</code>, <code>cpi</code>), et une colinéarité modérée sur les dimensions de développement (<code>gdp_log</code>, <code>life_expectancy</code>).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/corr_heatmap_2023.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>Les diagnostics montrent une colinéarité importante dans les deux années, surtout entre indicateurs institutionnels et de développement.</p>
<ol start="5" type="1">
<li><h5 id="comparaison-des-coefficients-standardisés-pour-2015-et-2023" class="anchored">Comparaison des coefficients standardisés pour 2015 et 2023</h5></li>
</ol>
<p>On compare les coefficients standardisés estimés sur les modèles réduits (sans <code>generosity</code>) pour 2015 et 2023. Les variables explicatives ayant été centrées-réduites, les coefficients sont comparables entre variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2015 standardisé</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>X15 <span class="ot">&lt;-</span> <span class="fu">scale</span>(df15[, vars_x_red])</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>df15_std <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">happiness_score =</span> df15<span class="sc">$</span>happiness_score, X15)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>mod_2015_std <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_score <span class="sc">~</span> ., <span class="at">data =</span> df15_std)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2023 standardisé</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>X23 <span class="ot">&lt;-</span> <span class="fu">scale</span>(df23[, vars_x_red])</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>df23_std <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">happiness_score =</span> df23<span class="sc">$</span>happiness_score, X23)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>mod_2023_std <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_score <span class="sc">~</span> ., <span class="at">data =</span> df23_std)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>coef15s <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(mod_2015_std); coef15s<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2015</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>coef23s <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(mod_2023_std); coef23s<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2023</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>coef_all_s <span class="ot">&lt;-</span> <span class="fu">rbind</span>(coef15s, coef23s)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/comparaison_coefficients_standardises_2015_2023.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>Le graphique met en évidence les variables qui contribuent le plus à l’explication du score de bonheur, entre 2015 et 2023.</p>
<p>En 2015, les effets standardisés dominants sont :</p>
<ul>
<li><code>gdp_log</code> et <code>life_expectancy</code>, qui ressortent comme les deux dimensions les plus associées positivement à <code>happiness_score</code>,</li>
<li><code>freedom_to_choose</code>, également positif et important,</li>
<li><code>government_effectiveness</code>, dont l’effet est négatif dans ce modèle multivarié, ce qui peut s’expliquer par la forte colinéarité avec d’autres indicateurs institutionnels (<code>cpi</code>, <code>gdp_log</code>), comme le montrent les VIF élevés.</li>
</ul>
<p>En 2023, la structure change :</p>
<ul>
<li><code>gdp_log</code> et <code>freedom_to_choose</code> deviennent les deux contributions positives les plus fortes,</li>
<li><code>life_expectancy</code> devient beaucoup plus faible, ce qui indique qu’à variables contrôlées identiques, son effet propre est moins marqué en 2023 dans ce modèle,</li>
<li><code>voice_accountability</code> apparaît plus important qu’en 2015, ce qui suggère un rôle institutionnel plus visible dans l’explication du bonheur en 2023.</li>
</ul>
<p>Les variables du marché du travail gardent un signal stable :</p>
<ul>
<li><code>unemployment_rate</code> reste négatif dans les deux années,</li>
<li><code>active_population_rate</code> est légèrement négatif, surtout en 2023.</li>
</ul>
<p>Enfin, les variables environnementales (<code>co2_emissions_per_capita</code>, <code>temperature_change_from_ghg</code>) ont des coefficients standardisés proches de zéro, ce qui indique qu’elles apportent peu d’information supplémentaire dans ce cadre linéaire une fois les variables socio-économiques et institutionnelles prises en compte.</p>
<p>Ces résultats doivent toutefois être interprétés avec prudence pour les variables institutionnelles (<code>cpi</code>, <code>government_effectiveness</code>), car la colinéarité est forte (VIF &gt; 10), ce qui peut rendre l’estimation de leurs effets propres instable.</p>
<ol start="6" type="1">
<li><h5 id="observations-influentes" class="anchored">Observations influentes</h5></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observations influentes 2015</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>cooks15 <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(mod_2015_red)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>lev15 <span class="ot">&lt;-</span> <span class="fu">hatvalues</span>(mod_2015_red)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>top_cook15 <span class="ot">&lt;-</span> <span class="fu">order</span>(cooks15, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>tab_infl_2015 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> top_cook15,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">country =</span> df15[top_cook15, <span class="st">"country"</span>],</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cook =</span> cooks15[top_cook15],</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">leverage =</span> lev15[top_cook15],</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">happiness_score =</span> df15[top_cook15, <span class="st">"happiness_score"</span>]</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(cook))</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tab_infl_2015, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">caption =</span> <span class="st">"Observations les plus influentes (2015)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Observations les plus influentes (2015)</caption>
<thead>
<tr class="header">
<th style="text-align: right;">id</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">cook</th>
<th style="text-align: right;">leverage</th>
<th style="text-align: right;">happiness_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">60</td>
<td style="text-align: left;">Hong Kong</td>
<td style="text-align: right;">0.0730</td>
<td style="text-align: right;">0.1142</td>
<td style="text-align: right;">5.474</td>
</tr>
<tr class="even">
<td style="text-align: right;">66</td>
<td style="text-align: left;">Nigeria</td>
<td style="text-align: right;">0.0698</td>
<td style="text-align: right;">0.2072</td>
<td style="text-align: right;">5.268</td>
</tr>
<tr class="odd">
<td style="text-align: right;">114</td>
<td style="text-align: left;">Gabon</td>
<td style="text-align: right;">0.0665</td>
<td style="text-align: right;">0.1789</td>
<td style="text-align: right;">3.896</td>
</tr>
<tr class="even">
<td style="text-align: right;">107</td>
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: right;">0.0577</td>
<td style="text-align: right;">0.1255</td>
<td style="text-align: right;">4.271</td>
</tr>
<tr class="odd">
<td style="text-align: right;">116</td>
<td style="text-align: left;">Cambodia</td>
<td style="text-align: right;">0.0423</td>
<td style="text-align: right;">0.0883</td>
<td style="text-align: right;">3.819</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En 2015, les 5 observations les plus influentes selon la distance de Cook sont les indices 60, 66, 114, 107 et 116. Leurs distances de Cook restent faibles (entre 0,042 et 0,073) et leurs valeurs de leverage sont modérées (entre 0,088 et 0,207).</p>
<p>Cela indique qu’il existe bien quelques pays un peu atypiques, mais aucun point ne domine fortement l’estimation du modèle. L’influence est donc présente mais limitée en 2015.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/cooks_2015.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observations influentes 2023</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>cooks23 <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(mod_2023_red)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>lev23 <span class="ot">&lt;-</span> <span class="fu">hatvalues</span>(mod_2023_red)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>top_cook23 <span class="ot">&lt;-</span> <span class="fu">order</span>(cooks23, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>tab_infl_2023 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> top_cook23,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">country =</span> df23[top_cook23, <span class="st">"country"</span>],</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cook =</span> cooks23[top_cook23],</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">leverage =</span> lev23[top_cook23],</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">happiness_score =</span> df23[top_cook23, <span class="st">"happiness_score"</span>]</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(cook))</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tab_infl_2023, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">caption =</span> <span class="st">"Observations les plus influentes (2023)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Observations les plus influentes (2023)</caption>
<thead>
<tr class="header">
<th style="text-align: right;">id</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">cook</th>
<th style="text-align: right;">leverage</th>
<th style="text-align: right;">happiness_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">124</td>
<td style="text-align: left;">Lebanon</td>
<td style="text-align: right;">0.2471</td>
<td style="text-align: right;">0.1653</td>
<td style="text-align: right;">2.3922</td>
</tr>
<tr class="even">
<td style="text-align: right;">121</td>
<td style="text-align: left;">Botswana</td>
<td style="text-align: right;">0.2026</td>
<td style="text-align: right;">0.1844</td>
<td style="text-align: right;">3.4353</td>
</tr>
<tr class="odd">
<td style="text-align: right;">83</td>
<td style="text-align: left;">South Africa</td>
<td style="text-align: right;">0.1408</td>
<td style="text-align: right;">0.4150</td>
<td style="text-align: right;">5.2746</td>
</tr>
<tr class="even">
<td style="text-align: right;">116</td>
<td style="text-align: left;">India</td>
<td style="text-align: right;">0.0736</td>
<td style="text-align: right;">0.1238</td>
<td style="text-align: right;">4.0358</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: left;">Bahrain</td>
<td style="text-align: right;">0.0714</td>
<td style="text-align: right;">0.3143</td>
<td style="text-align: right;">6.1732</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En 2023, l’influence est nettement plus marquée. Les 5 observations les plus influentes sont 124, 121, 83, 116 et 40, avec des distances de Cook beaucoup plus élevées (jusqu’à 0,247 et 0,203 pour 124 et 121). On note aussi que certaines observations combinent leverage élevé et influence importante, en particulier :</p>
<ul>
<li>83 avec un leverage très élevé (0,415),</li>
<li>40 avec un leverage élevé (0,314),</li>
<li>ainsi que 121 et 124 avec un leverage autour de 0,165–0,184.</li>
</ul>
<p>Ces résultats confirment ce que suggéraient les graphes de diagnostic : en 2023, quelques pays pèsent davantage sur l’estimation, ce qui peut expliquer une normalité moins bonne des résidus et une sensibilité plus forte de certains coefficients.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/cooks_2023.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<ol start="7" type="1">
<li><h5 id="analyse-de-robustesse" class="anchored">Analyse de robustesse</h5></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># retirer les 5 plus influents 2015</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df15_rob <span class="ot">&lt;-</span> df15[<span class="sc">-</span>top_cook15, ]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>mod_2015_red_rob <span class="ot">&lt;-</span> <span class="fu">lm</span>(form_red, <span class="at">data =</span> df15_rob)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2015_red_rob)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form_red, data = df15_rob)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.30141 -0.28304 -0.01021  0.36590  1.30656 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -4.784982   1.376671  -3.476 0.000735 ***
gdp_log                      0.521392   0.157073   3.319 0.001231 ** 
life_expectancy              0.064396   0.016612   3.877 0.000182 ***
freedom_to_choose            1.387799   0.318544   4.357 3.02e-05 ***
cpi                          0.008884   0.008157   1.089 0.278539    
unemployment_rate           -0.032254   0.011250  -2.867 0.004983 ** 
active_population_rate      -0.010248   0.013971  -0.734 0.464840    
urban_population_rate        0.003608   0.004283   0.842 0.401520    
voice_accountability         0.056299   0.101838   0.553 0.581524    
government_effectiveness    -0.363376   0.200792  -1.810 0.073122 .  
co2_emissions_per_capita    -0.014381   0.017003  -0.846 0.399532    
temperature_change_from_ghg  1.641506   1.611709   1.018 0.310722    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5261 on 108 degrees of freedom
Multiple R-squared:  0.8103,    Adjusted R-squared:  0.7909 
F-statistic: 41.93 on 11 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># comparaison coefficients</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef_full =</span> <span class="fu">coef</span>(mod_2015_red),</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef_rob  =</span> <span class="fu">coef</span>(mod_2015_red_rob)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               coef_full     coef_rob
(Intercept)                 -3.845048627 -4.784982372
gdp_log                      0.522435303  0.521391587
life_expectancy              0.051750973  0.064396390
freedom_to_choose            1.176073728  1.387799118
cpi                          0.007576108  0.008883890
unemployment_rate           -0.033276346 -0.032254029
active_population_rate      -0.010911591 -0.010247574
urban_population_rate        0.005492170  0.003607574
voice_accountability         0.158644781  0.056298878
government_effectiveness    -0.381648521 -0.363375562
co2_emissions_per_capita    -0.002050359 -0.014381106
temperature_change_from_ghg  2.113723876  1.641505886</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/stabilite_coef_2015.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>Après retrait des 5 observations les plus influentes (indices 60, 66, 114, 107, 116), le modèle reste globalement très proche, mais certains résultats évoluent.</p>
<ul>
<li>Qualité d’ajustement : elle augmente nettement
<ul>
<li>R² passe de 0,7701 à 0,8103</li>
<li>R² ajusté passe de 0,7477 à 0,7909</li>
<li>l’erreur standard résiduelle baisse de 0,5784 à 0,5261</li>
</ul></li>
<li>Coefficients stables (robustes) :
<ul>
<li><code>gdp_log</code> reste quasi identique (0,5224 puis 0,5214) et reste significatif (p = 0,0012)</li>
<li><code>unemployment_rate</code> reste très proche (-0,0333 puis -0,0323) et significatif (p = 0,0050)</li>
</ul></li>
<li>Coefficients qui changent en amplitude :
<ul>
<li><code>life_expectancy</code> augmente (0,0518 puis 0,0644) et devient encore plus significatif (p = 0,00018)</li>
<li><code>freedom_to_choose</code> augmente (1,1761 puis 1,3878) et devient plus significatif (p = 3.02e-05)</li>
</ul></li>
<li>Variables sensibles aux points influents :
<ul>
<li><code>voice_accountability</code> baisse fortement (0,1586 puis 0,0563) et devient clairement non significatif (p = 0,58)</li>
<li><code>co2_emissions_per_capita</code> change d’amplitude (-0,0021 puis -0,0144) mais reste non significatif (p = 0,40)</li>
<li><code>government_effectiveness</code> reste négatif et devient “limite” au seuil 10% (p = 0,073)</li>
</ul></li>
</ul>
<p>Les déterminants principaux du modèle (<code>gdp_log</code>, <code>life_expectancy</code>, <code>freedom_to_choose</code>, <code>unemployment_rate</code>) restent cohérents et même renforcés après retrait des points influents. En revanche, l’effet de certaines variables institutionnelles (<code>voice_accountability</code>) est peu robuste.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># retirer les 5 plus influents 2023</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>df23_rob <span class="ot">&lt;-</span> df23[<span class="sc">-</span>top_cook23, ]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>mod_2023_red_rob <span class="ot">&lt;-</span> <span class="fu">lm</span>(form_red, <span class="at">data =</span> df23_rob)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2023_red_rob)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form_red, data = df23_rob)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.13783 -0.21860  0.01266  0.23179  1.02139 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -0.8779719  1.0511086  -0.835  0.40540    
gdp_log                      0.5542575  0.1125974   4.922 3.09e-06 ***
life_expectancy              0.0058809  0.0144967   0.406  0.68578    
freedom_to_choose            2.1053369  0.3105510   6.779 6.65e-10 ***
cpi                          0.0009195  0.0075548   0.122  0.90335    
unemployment_rate           -0.0203473  0.0140830  -1.445  0.15141    
active_population_rate      -0.0200432  0.0131704  -1.522  0.13097    
urban_population_rate        0.0068204  0.0033071   2.062  0.04157 *  
voice_accountability         0.2515120  0.0847999   2.966  0.00372 ** 
government_effectiveness    -0.2289515  0.1595522  -1.435  0.15419    
co2_emissions_per_capita     0.0219327  0.0169762   1.292  0.19913    
temperature_change_from_ghg  0.1514112  1.2806440   0.118  0.90610    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4546 on 108 degrees of freedom
Multiple R-squared:  0.8442,    Adjusted R-squared:  0.8283 
F-statistic: 53.19 on 11 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># comparaison coefficients</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef_full =</span> <span class="fu">coef</span>(mod_2023_red),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef_rob  =</span> <span class="fu">coef</span>(mod_2023_red_rob)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                coef_full      coef_rob
(Intercept)                 -0.7942228973 -0.8779718736
gdp_log                      0.6145871993  0.5542574958
life_expectancy              0.0044581490  0.0058809326
freedom_to_choose            2.2620651809  2.1053368820
cpi                         -0.0003962587  0.0009195435
unemployment_rate           -0.0265505835 -0.0203473066
active_population_rate      -0.0280656665 -0.0200431507
urban_population_rate        0.0053056318  0.0068204245
voice_accountability         0.2525579039  0.2515119723
government_effectiveness    -0.2076209925 -0.2289515103
co2_emissions_per_capita     0.0180485658  0.0219326514
temperature_change_from_ghg -0.0641539258  0.1514111734</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/stabilite_coef_2023.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>Après retrait des 5 observations les plus influentes (124, 121, 83, 116, 40), le modèle change davantage sur certaines variables.</p>
<ul>
<li><p>Qualité d’ajustement : elle augmente nettement</p>
<ul>
<li>R² passe de 0,8079 à 0,8442</li>
<li>R² ajusté passe de 0,7892 à 0,8283</li>
<li>l’erreur standard résiduelle baisse de 0,5239 à 0,4546</li>
</ul></li>
<li><p>Coefficients très robustes :</p>
<ul>
<li><code>voice_accountability</code> est pratiquement inchangé (0,2526 puis 0,2515) et reste significatif (p = 0,0037)</li>
<li><code>gdp_log</code> reste positif ( 0,6146 puis 0,5543 ) et significatif (p = 3.09e-06)</li>
<li><code>freedom_to_choose</code> reste positif ( 2,2621 puis 2,1053 ) et très significatif (p = 6.65e-10)</li>
</ul></li>
<li><p>Coefficients qui perdent leur significativité :</p>
<ul>
<li><code>unemployment_rate</code> devient non significatif (p = 0,151)</li>
<li><code>active_population_rate</code> devient non significatif (p = 0,131) Ces deux variables restent négatives, mais leur “effet propre” n’est plus statistiquement confirmé après retrait des points influents.</li>
</ul></li>
<li><p>Variable qui devient significative :</p>
<ul>
<li><code>urban_population_rate</code> devient significatif au seuil de 5% (p = 0,0416) et son coefficient augmente (0,0053 puis 0,0068)</li>
</ul></li>
<li><p>Signes instables :</p>
<ul>
<li><code>temperature_change_from_ghg</code> change de signe (-0,0642 puis 0,1514) et reste non significatif (p = 0,906). Cela confirme que cette variable n’a pas un effet stable dans ce modèle.</li>
</ul></li>
</ul>
<p>Les résultats les plus stables sont <code>gdp_log</code>, <code>freedom_to_choose</code> et <code>voice_accountability</code>. En revanche, <code>unemployment_rate</code> et <code>active_population_rate</code> apparaissent sensibles à quelques pays influents, ce qui impose de nuancer leur interprétation.</p>
<ol start="8" type="1">
<li><h5 id="le-modèle-qui-généralise-le-mieux" class="anchored">Le modèle qui généralise le mieux</h5></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>eval_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(df, models, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>) {</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  folds <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">vfold_cv</span>(df, <span class="at">v =</span> v, <span class="at">repeats =</span> repeats)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map_dfr</span>(folds<span class="sc">$</span>splits, <span class="cf">function</span>(split) {</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    train <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">analysis</span>(split)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    test  <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">assessment</span>(split)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    purrr<span class="sc">::</span><span class="fu">map_dfr</span>(<span class="fu">names</span>(models), <span class="cf">function</span>(mn) {</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>      fit <span class="ot">&lt;-</span> models[[mn]](train)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>      pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> test)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>      obs <span class="ot">&lt;-</span> test<span class="sc">$</span>happiness_score</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>      rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((obs <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>      mae  <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(obs <span class="sc">-</span> pred), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>      r2   <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>((obs <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>((obs <span class="sc">-</span> <span class="fu">mean</span>(obs, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">data.frame</span>(<span class="at">model =</span> mn, <span class="at">RMSE =</span> rmse, <span class="at">MAE =</span> mae, <span class="at">R2 =</span> r2)</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>  res <span class="sc">%&gt;%</span></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(model) <span class="sc">%&gt;%</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">RMSE_mean =</span> <span class="fu">mean</span>(RMSE), <span class="at">RMSE_sd =</span> <span class="fu">sd</span>(RMSE),</span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">MAE_mean  =</span> <span class="fu">mean</span>(MAE),  <span class="at">MAE_sd  =</span> <span class="fu">sd</span>(MAE),</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">R2_mean   =</span> <span class="fu">mean</span>(R2),   <span class="at">R2_sd   =</span> <span class="fu">sd</span>(R2),</span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(RMSE_mean)</span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Formules stepAIC déjà sélectionnées plus haut dans ton notebook</span></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a>form_step_2015 <span class="ot">&lt;-</span> <span class="fu">formula</span>(mod_2015_step)</span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>form_step_2023 <span class="ot">&lt;-</span> <span class="fu">formula</span>(mod_2023_step)</span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèles à comparer (formules fixées)</span></span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a>models_2015 <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Complet"</span> <span class="ot">=</span> <span class="cf">function</span>(train) <span class="fu">lm</span>(form, <span class="at">data =</span> train),</span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Réduit (sans generosity)"</span> <span class="ot">=</span> <span class="cf">function</span>(train) <span class="fu">lm</span>(form_red, <span class="at">data =</span> train),</span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a>  <span class="st">"StepAIC (formule fixée)"</span> <span class="ot">=</span> <span class="cf">function</span>(train) <span class="fu">lm</span>(form_step_2015, <span class="at">data =</span> train)</span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-45"><a href="#cb38-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-46"><a href="#cb38-46" aria-hidden="true" tabindex="-1"></a>models_2023 <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb38-47"><a href="#cb38-47" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Complet"</span> <span class="ot">=</span> <span class="cf">function</span>(train) <span class="fu">lm</span>(form, <span class="at">data =</span> train),</span>
<span id="cb38-48"><a href="#cb38-48" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Réduit (sans generosity)"</span> <span class="ot">=</span> <span class="cf">function</span>(train) <span class="fu">lm</span>(form_red, <span class="at">data =</span> train),</span>
<span id="cb38-49"><a href="#cb38-49" aria-hidden="true" tabindex="-1"></a>  <span class="st">"StepAIC (formule fixée)"</span> <span class="ot">=</span> <span class="cf">function</span>(train) <span class="fu">lm</span>(form_step_2023, <span class="at">data =</span> train)</span>
<span id="cb38-50"><a href="#cb38-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-51"><a href="#cb38-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-52"><a href="#cb38-52" aria-hidden="true" tabindex="-1"></a><span class="co"># CV 2015</span></span>
<span id="cb38-53"><a href="#cb38-53" aria-hidden="true" tabindex="-1"></a>cv15 <span class="ot">&lt;-</span> <span class="fu">eval_cv</span>(df15, models_2015, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>)</span>
<span id="cb38-54"><a href="#cb38-54" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(cv15, <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb38-55"><a href="#cb38-55" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Validation croisée 10-fold répétée (2015) : comparaison des modèles"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Validation croisée 10-fold répétée (2015) : comparaison des modèles</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">RMSE_mean</th>
<th style="text-align: right;">RMSE_sd</th>
<th style="text-align: right;">MAE_mean</th>
<th style="text-align: right;">MAE_sd</th>
<th style="text-align: right;">R2_mean</th>
<th style="text-align: right;">R2_sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">StepAIC (formule fixée)</td>
<td style="text-align: right;">0.5879</td>
<td style="text-align: right;">0.1145</td>
<td style="text-align: right;">0.4737</td>
<td style="text-align: right;">0.0957</td>
<td style="text-align: right;">0.6873</td>
<td style="text-align: right;">0.1419</td>
</tr>
<tr class="even">
<td style="text-align: left;">Réduit (sans generosity)</td>
<td style="text-align: right;">0.5977</td>
<td style="text-align: right;">0.1161</td>
<td style="text-align: right;">0.4820</td>
<td style="text-align: right;">0.0969</td>
<td style="text-align: right;">0.6764</td>
<td style="text-align: right;">0.1468</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Complet</td>
<td style="text-align: right;">0.6034</td>
<td style="text-align: right;">0.1180</td>
<td style="text-align: right;">0.4872</td>
<td style="text-align: right;">0.0976</td>
<td style="text-align: right;">0.6702</td>
<td style="text-align: right;">0.1492</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Le modèle qui généralise le mieux est StepAIC.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CV 2023</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>cv23 <span class="ot">&lt;-</span> <span class="fu">eval_cv</span>(df23, models_2023, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(cv23, <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Validation croisée 10-fold répétée (2023) : comparaison des modèles"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Validation croisée 10-fold répétée (2023) : comparaison des modèles</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">RMSE_mean</th>
<th style="text-align: right;">RMSE_sd</th>
<th style="text-align: right;">MAE_mean</th>
<th style="text-align: right;">MAE_sd</th>
<th style="text-align: right;">R2_mean</th>
<th style="text-align: right;">R2_sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">StepAIC (formule fixée)</td>
<td style="text-align: right;">0.5301</td>
<td style="text-align: right;">0.1639</td>
<td style="text-align: right;">0.4061</td>
<td style="text-align: right;">0.1194</td>
<td style="text-align: right;">0.7191</td>
<td style="text-align: right;">0.1644</td>
</tr>
<tr class="even">
<td style="text-align: left;">Réduit (sans generosity)</td>
<td style="text-align: right;">0.5519</td>
<td style="text-align: right;">0.1647</td>
<td style="text-align: right;">0.4175</td>
<td style="text-align: right;">0.1209</td>
<td style="text-align: right;">0.6960</td>
<td style="text-align: right;">0.1750</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Complet</td>
<td style="text-align: right;">0.5526</td>
<td style="text-align: right;">0.1653</td>
<td style="text-align: right;">0.4163</td>
<td style="text-align: right;">0.1265</td>
<td style="text-align: right;">0.6954</td>
<td style="text-align: right;">0.1764</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Le modèle qui généralise le mieux est StepAIC. On observe des écarts encore plus marqués.</p>
<p>Sur 2015 comme sur 2023, le modèle StepAIC (formule fixée) obtient la meilleure performance prédictive hors échantillon. Le modèle réduit sans <code>generosity</code> arrive en deuxième, et le modèle complet est le moins performant.</p>
<ol start="9" type="1">
<li><h5 id="régularisation-ridgelasso" class="anchored">Régularisation (Ridge/Lasso)</h5></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CV Ridge/Lasso via rsample + glmnet</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>eval_cv_glmnet <span class="ot">&lt;-</span> <span class="cf">function</span>(df, vars_x, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="dv">0</span>) {</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  folds <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">vfold_cv</span>(df, <span class="at">v =</span> v, <span class="at">repeats =</span> repeats)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map_dfr</span>(folds<span class="sc">$</span>splits, <span class="cf">function</span>(split) {</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    train <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">analysis</span>(split)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    test  <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">assessment</span>(split)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Matrices modèle (glmnet veut des matrices numériques)</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    x_train <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"happiness_score ~"</span>, <span class="fu">paste</span>(vars_x, <span class="at">collapse =</span> <span class="st">" + "</span>))),</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> train</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>    )[ , <span class="sc">-</span><span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span>]  <span class="co"># enlever intercept</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>    y_train <span class="ot">&lt;-</span> train<span class="sc">$</span>happiness_score</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>    x_test <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"happiness_score ~"</span>, <span class="fu">paste</span>(vars_x, <span class="at">collapse =</span> <span class="st">" + "</span>))),</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> test</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>    )[ , <span class="sc">-</span><span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>    y_test <span class="ot">&lt;-</span> test<span class="sc">$</span>happiness_score</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># CV interne glmnet pour choisir lambda sur le train uniquement</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>    cvfit <span class="ot">&lt;-</span> glmnet<span class="sc">::</span><span class="fu">cv.glmnet</span>(</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> x_train, <span class="at">y =</span> y_train,</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">alpha =</span> alpha,</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">standardize =</span> <span class="cn">TRUE</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(cvfit, <span class="at">newx =</span> x_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>))</span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>    rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((y_test <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>    mae  <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(y_test <span class="sc">-</span> pred), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a>    r2   <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>((y_test <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>((y_test <span class="sc">-</span> <span class="fu">mean</span>(y_test, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">RMSE =</span> rmse, <span class="at">MAE =</span> mae, <span class="at">R2 =</span> r2)</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a>  res <span class="sc">%&gt;%</span></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a>      <span class="at">RMSE_mean =</span> <span class="fu">mean</span>(RMSE), <span class="at">RMSE_sd =</span> <span class="fu">sd</span>(RMSE),</span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">MAE_mean  =</span> <span class="fu">mean</span>(MAE),  <span class="at">MAE_sd  =</span> <span class="fu">sd</span>(MAE),</span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">R2_mean   =</span> <span class="fu">mean</span>(R2),   <span class="at">R2_sd   =</span> <span class="fu">sd</span>(R2)</span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># On utilise vars_x_red (sans generosity) comme pour tes modèles réduits</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>res_ridge_2015 <span class="ot">&lt;-</span> <span class="fu">eval_cv_glmnet</span>(df15, vars_x_red, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>res_lasso_2015 <span class="ot">&lt;-</span> <span class="fu">eval_cv_glmnet</span>(df15, vars_x_red, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>res_enet_2015  <span class="ot">&lt;-</span> <span class="fu">eval_cv_glmnet</span>(df15, vars_x_red, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>tab_glmnet_2015 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">"Ridge (alpha=0)"</span>,  res_ridge_2015),</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">"Lasso (alpha=1)"</span>,  res_lasso_2015),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">"Elastic Net (alpha=0.5)"</span>, res_enet_2015)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(RMSE_mean)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tab_glmnet_2015, <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Validation croisée 10-fold répétée (2015) : Ridge / Lasso / Elastic Net (glmnet)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Validation croisée 10-fold répétée (2015) : Ridge / Lasso / Elastic Net (glmnet)</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">RMSE_mean</th>
<th style="text-align: right;">RMSE_sd</th>
<th style="text-align: right;">MAE_mean</th>
<th style="text-align: right;">MAE_sd</th>
<th style="text-align: right;">R2_mean</th>
<th style="text-align: right;">R2_sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ridge (alpha=0)</td>
<td style="text-align: right;">0.5944</td>
<td style="text-align: right;">0.1101</td>
<td style="text-align: right;">0.4890</td>
<td style="text-align: right;">0.0952</td>
<td style="text-align: right;">0.6822</td>
<td style="text-align: right;">0.1367</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lasso (alpha=1)</td>
<td style="text-align: right;">0.5990</td>
<td style="text-align: right;">0.1197</td>
<td style="text-align: right;">0.4916</td>
<td style="text-align: right;">0.1075</td>
<td style="text-align: right;">0.6502</td>
<td style="text-align: right;">0.2136</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elastic Net (alpha=0.5)</td>
<td style="text-align: right;">0.6018</td>
<td style="text-align: right;">0.1081</td>
<td style="text-align: right;">0.4911</td>
<td style="text-align: right;">0.0933</td>
<td style="text-align: right;">0.6443</td>
<td style="text-align: right;">0.2101</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En 2015, StepAIC est légèrement plus efficace que le Ridge (RMSE moyen StepAIC ≈ 0,588 contre RMSE moyen Ridge ≈ 0,594).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>res_ridge_2023 <span class="ot">&lt;-</span> <span class="fu">eval_cv_glmnet</span>(df23, vars_x_red, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>res_lasso_2023 <span class="ot">&lt;-</span> <span class="fu">eval_cv_glmnet</span>(df23, vars_x_red, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>res_enet_2023  <span class="ot">&lt;-</span> <span class="fu">eval_cv_glmnet</span>(df23, vars_x_red, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>tab_glmnet_2023 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">"Ridge (alpha=0)"</span>,  res_ridge_2023),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">"Lasso (alpha=1)"</span>,  res_lasso_2023),</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">"Elastic Net (alpha=0.5)"</span>, res_enet_2023)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(RMSE_mean)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tab_glmnet_2023, <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Validation croisée 10-fold répétée (2023) : Ridge / Lasso / Elastic Net (glmnet)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Validation croisée 10-fold répétée (2023) : Ridge / Lasso / Elastic Net (glmnet)</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">RMSE_mean</th>
<th style="text-align: right;">RMSE_sd</th>
<th style="text-align: right;">MAE_mean</th>
<th style="text-align: right;">MAE_sd</th>
<th style="text-align: right;">R2_mean</th>
<th style="text-align: right;">R2_sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Elastic Net (alpha=0.5)</td>
<td style="text-align: right;">0.5471</td>
<td style="text-align: right;">0.1527</td>
<td style="text-align: right;">0.4111</td>
<td style="text-align: right;">0.1145</td>
<td style="text-align: right;">0.7076</td>
<td style="text-align: right;">0.1400</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lasso (alpha=1)</td>
<td style="text-align: right;">0.5484</td>
<td style="text-align: right;">0.1359</td>
<td style="text-align: right;">0.4100</td>
<td style="text-align: right;">0.0903</td>
<td style="text-align: right;">0.7018</td>
<td style="text-align: right;">0.1640</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ridge (alpha=0)</td>
<td style="text-align: right;">0.5502</td>
<td style="text-align: right;">0.1346</td>
<td style="text-align: right;">0.4132</td>
<td style="text-align: right;">0.0982</td>
<td style="text-align: right;">0.7211</td>
<td style="text-align: right;">0.1035</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En 2023, StepAIC est encore plus efficace que le Ridge (RMSE moyen StepAIC ≈ 0,534 contre RMSE moyen Ridge ≈ 0,550 et Elastic Net ≈ 0,547).</p>
<p>Dans nos données, la régularisation (Ridge/Lasso) ne surpasse pas StepAIC en RMSE, mais elle peut être utilisé comme une réponse à la colinéarité car elle stabilise les coefficients et limite la variance des estimations.</p>
<ol start="10" type="1">
<li><h5 id="comparaison-globale-de-tous-les-modèles" class="anchored">Comparaison globale de tous les modèles</h5></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figure/regression/comparaison_globale_modeles_rmse.png" class="img-fluid figure-img" width="850"></p>
</figure>
</div>
</div>
</div>
<p>L’objectif était de modéliser le score de bonheur (<code>happiness_score</code>) en 2015 et en 2023 à partir d’un ensemble de variables socio-économiques, institutionnelles et environnementales, puis de choisir un modèle qui généralise le mieux.</p>
<p>Sur les deux années, les modèles linéaires ont un bon pouvoir explicatif en ajustement (R² ≈ 0,77 en 2015 et ≈ 0,81 en 2023 pour le modèle complet). Les déterminants les plus stables et les plus robustes sont <code>gdp_log</code> et <code>freedom_to_choose</code>, qui ressortent positifs dans les deux périodes. En 2015, <code>life_expectancy</code> est également un contributeur important, alors qu’en 2023 son effet propre devient faible une fois les autres variables contrôlées. Côté institutionnel, <code>voice_accountability</code> apparaît plus nettement en 2023. Les variables environnementales apportent peu d’information supplémentaire dans ce cadre linéaire, une fois les variables de développement et institutionnelles prises en compte.</p>
<p>Les diagnostics mettent en évidence deux limites importantes. D’abord, une colinéarité marquée, surtout autour du bloc institutionnel et développement (<code>cpi</code>, <code>government_effectiveness</code>, et <code>gdp_log</code>), confirmée par des VIF élevés. Ensuite, la présence d’observations influentes, particulièrement en 2023, ce qui impose de rester prudent dans l’interprétation causale et même dans l’interprétation fine de certains coefficients.</p>
<p>Pour le choix de modèle, la validation croisée montre que le modèle StepAIC (formule fixée) est le meilleur en prédiction hors échantillon sur les deux années. En 2015, il obtient un RMSE moyen d’environ 0,588, légèrement meilleur que Ridge (≈ 0,594) et meilleur que les modèles complet et réduit. En 2023, l’écart est plus net, avec un RMSE moyen d’environ 0,530 pour StepAIC, contre ≈ 0,55 pour Ridge et Elastic Net, et ≈ 0,552 pour les modèles complet et réduit. Le graphique final synthétise bien ce résultat, StepAIC est systématiquement parmi les plus performants, et 2023 présente globalement des RMSE plus faibles que 2015.</p>
<p>Enfin, la régularisation (Ridge, Lasso, Elastic Net) ne surpasse pas StepAIC en RMSE dans ces données, mais elle reste pertinente comme réponse à la colinéarité car elle stabilise l’estimation des coefficients et peut limiter la variance. Par la suite, si l’objectif prioritaire devient la prédiction, StepAIC sera le meilleur choix. Si l’objectif nécessite davantage la robustesse des coefficients dans un contexte colinéaire, Ridge ou Elastic Net peuvent rester intéressants, à condition d’accepter une performance prédictive légèrement inférieure dans les résultats.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>